language: node_js

node_js:
  - 0.10

env:
  global:
    - SAUCE_USERNAME=igorzg
    - SAUCE_ACCESS_KEY=2b2136fe-063d-4485-9262-e6f57903bbb0

install:
  - nvm install 0.12.0
  - npm install --save-dev
  - npm install -g gulp
script:
  - gulp test