language: node_js

node_js:
  - "4.0.0"

env:
  global:
    - SAUCE_USERNAME=igorzg
    - SAUCE_ACCESS_KEY=2b2136fe-063d-4485-9262-e6f57903bbb0

install:
  - npm install --save-dev
  - npm install -g gulp
  - npm install -g gulp-cli
script:
  - gulp test